### ISSUE TITLE
Cleaner folder structure

### ISSUE THREAD

**Issue by ArfaaShariff** [danielchristopher1/RxSwift-MVVM-Architecture#8]
- Create folders in your file system, where you have your project files, then create a group with the same folder name in XCode. It will act like any other group, but now be linked to the folder on the file system.

- Adding files to that group in Xcode now adds them to the folder in the file system.

- Much cleaner way of working and helps when locating files in big projects. Keeps git cleaner too.

**Comment by ArfaaShariff** [comment]
I have sent a pull request for this issue on branch folder-structure

**Comment by danielchristopher1** [comment]
Thanks! Resolved
